### PR TITLE
Convertphp

### PR DESCRIPTION
**Pull request by Kunal-Deshpande**
Added express js server.
Can login and logout.
Tested voting with the changes.
Changed the api end point to api.steemit.com

The php file are intact. If php files are not needed then can be deleted.

### CODE REVIEW

**Comment by hrj** [comment]
This may not be complete. @Kunal-Deshpande You need to check all UI functionality and which API endpoints are getting called. And if they are returning errors migrate them from PHP to JS. The PHP code is minimal so migrating should be easy.

**Comment by hrj** [comment]
Please also update README file with instructions for running this branch.

**Comment by hrj** [comment]
@Kunal-Deshpande If you make the following change:
```
--- a/app/Resources/views/base.html.twig
+++ b/app/Resources/views/base.html.twig
@@ -23,7 +23,7 @@
         let sf = {
           appName: '{{ app_name }}',
           redirectUri: '{{ url }}/auth',
-          host: '{{ host }}',
+          host: '{{ host }}/',
           access_token: {{ accesstoken }},
           username: {{ username }}
```

You will see requests being made to node server for mentions, followers and votes. Then you will be able to implement and test it.

**Comment by mktcode** [comment]
ths so much :)

**Pull request merged**
